# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19cdadd043f07e88ef82c857b446269714f3772df5382fabc4ef9c472e7eb74167aef11635d1e5e489adc44d22872cd5ddfa959dadea4edf931a0de7e86d7aa5

test:
  secret_key_base: 257d56fa802ac548aa5108efe8e9d265ecf494a9d08f294fe4059ef5f42f37c040506193580790e15172cec5f63d49499b9e98fa2d512ce8fdf79757402cec0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
